collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3783536
  brandStrength: 0.6593592
  lightness: 0.5650656
  brandColors:
    - '#070705'
    - '#E1EFFC'
    - '#4E3123'
    - '#276C3D'
    - '#76B157'
  rhythmicContrast: 0.4673093
typography_spectrum: 0.5300161
layout_spectrum: 0.5421585
name: BFMG
